manifest = "46b3ef1492cf8bd36f9fa4a9e9878a9f9d70d97d6315be40cb951b4f893566ca"

[[dependency]]
package = "github.com/iwatakeshi/latte"
target = "//:latte"

[[dependency]]
package = "github.com/iwatakeshi/to_string"
target = "//:to_string"

[lock."github.com/iwatakeshi/bench"]
versions = [ "branch=master" ]
revision = "0fe9e1605ee18500fed023ef364abc1cbf322d0a"

[lock."github.com/iwatakeshi/latte"]
versions = [ "branch=master" ]
revision = "124fbe3381d6015e703f002f999770d05b7ad0b8"

[lock."github.com/iwatakeshi/to_string"]
versions = [ "tag=1.0.0-alpha" ]
revision = "b02f78ebbaf245b137e9bb1e4299aced026910a3"
