manifest = "46b3ef1492cf8bd36f9fa4a9e9878a9f9d70d97d6315be40cb951b4f893566ca"

[[dependency]]
package = "github.com/iwatakeshi/latte"
target = "//:latte"

[[dependency]]
package = "github.com/iwatakeshi/to_string"
target = "//:to_string"

[lock."github.com/iwatakeshi/bench"]
versions = [ "branch=master" ]
revision = "f06b11603b7eb3ed8ca7556e89a60c3c5df7c00a"

[lock."github.com/iwatakeshi/latte"]
versions = [ "branch=master" ]
revision = "ec0c31092af3d9b42e757a6bb375d817ff522376"

[lock."github.com/iwatakeshi/to_string"]
versions = [ "tag=1.0.0-alpha" ]
revision = "b02f78ebbaf245b137e9bb1e4299aced026910a3"
